/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMAD PAHRUL GUNAWAN
 */
public class MenuUtamaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtamaAdmin
     */
    
    public MenuUtamaAdmin() {
    initComponents();
    // Menetapkan judul frame
    setTitle("Admin - Main Menu");
    // Mengatur tampilan frame ke mode layar penuh
    setExtendedState(MAXIMIZED_BOTH);
    try {
        // Membaca tema yang disimpan dari file tema.txt
        FileReader fr = new FileReader("src/tema.txt");
        BufferedReader br = new BufferedReader(fr);
        // Memeriksa tema yang telah disimpan dan menerapkan tema gelap jika tema adalah "Dark"
        if (br.readLine().equals("Dark")) {
            tema();
        }
    } catch (Exception e) {
        // Menangani exception (jika ada) dengan tidak melakukan apa pun
        }
    } 
    
    private void tema(){
        jDesktopPane1.setBackground(Color.BLACK);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Kembali = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Karyawan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Tema = new javax.swing.JMenuItem();
        Sandi1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bacgdound toko buku.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(0, 0, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-menu-32.png"))); // NOI18N
        jMenu1.setText("MENU");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Kembali.setBackground(new java.awt.Color(0, 0, 255));
        Kembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Kembali.setForeground(new java.awt.Color(0, 0, 255));
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-back-32.png"))); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jMenu1.add(Kembali);

        Keluar.setBackground(new java.awt.Color(0, 0, 255));
        Keluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(0, 0, 255));
        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-logout-32.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(Keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-database-32.png"))); // NOI18N
        jMenu2.setText("DATA");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Karyawan.setBackground(new java.awt.Color(0, 0, 255));
        Karyawan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Karyawan.setForeground(new java.awt.Color(0, 0, 255));
        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-hard-working-32.png"))); // NOI18N
        Karyawan.setText("Data Karyawan");
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(Karyawan);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 255));
        jMenu3.setForeground(new java.awt.Color(0, 0, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-setting-32.png"))); // NOI18N
        jMenu3.setText("PENGATURAN");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Tema.setBackground(new java.awt.Color(0, 0, 255));
        Tema.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Tema.setForeground(new java.awt.Color(0, 0, 255));
        Tema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-theme-32.png"))); // NOI18N
        Tema.setText("Tema");
        Tema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemaActionPerformed(evt);
            }
        });
        jMenu3.add(Tema);

        Sandi1.setBackground(new java.awt.Color(0, 0, 255));
        Sandi1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Sandi1.setForeground(new java.awt.Color(0, 0, 255));
        Sandi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-password-key-32.png"))); // NOI18N
        Sandi1.setText("Ubah Sandi");
        Sandi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sandi1ActionPerformed(evt);
            }
        });
        jMenu3.add(Sandi1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
    // Memastikan bahwa jDesktopPane1 tergambar kembali (repaint)
    jDesktopPane1.repaint();
    // Membuat instance baru dari kelas DataKaryawan
    DataKaryawan DP = new DataKaryawan();
    // Menambahkan instance DataKaryawan ke jDesktopPane1
    jDesktopPane1.add(DP);
    // Mendapatkan dimensi dari jDesktopPane1 dan DataKaryawan
    Dimension induk = jDesktopPane1.getSize();
    Dimension anak = DP.getSize();
    // Menetapkan lokasi DataKaryawan agar berada di tengah jDesktopPane1
    DP.setLocation((induk.width - anak.width) / 2, (induk.height - anak.height) / 2);
    // Menampilkan tampilan DataKaryawan
    DP.setVisible(true);
    }//GEN-LAST:event_KaryawanActionPerformed

    private void TemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemaActionPerformed
    // Memastikan bahwa jDesktopPane1 tergambar kembali (repaint)
    jDesktopPane1.repaint();
    // Membuat instance baru dari kelas Tema
    Tema t = new Tema();
    // Menambahkan instance Tema ke jDesktopPane1
    jDesktopPane1.add(t);
    // Mendapatkan dimensi dari jDesktopPane1 dan Tema
    Dimension induk = jDesktopPane1.getSize();
    Dimension anak = t.getSize();
    // Menetapkan lokasi Tema agar berada di tengah jDesktopPane1
    t.setLocation((induk.width - anak.width) / 2, (induk.height - anak.height) / 2);
    // Memberikan akses dengan parameter "Owner" ke tampilan Tema
    t.akses("Owner");
    // Menampilkan tampilan Tema
    t.setVisible(true);
    }//GEN-LAST:event_TemaActionPerformed

    private void Sandi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sandi1ActionPerformed
    // Memastikan bahwa jDesktopPane1 tergambar kembali (repaint)
    jDesktopPane1.repaint();
    // Membuat instance baru dari kelas UbahPassword
    UbahPassword up = new UbahPassword();
    // Menambahkan instance UbahPassword ke jDesktopPane1
    jDesktopPane1.add(up);
    // Mendapatkan dimensi dari jDesktopPane1 dan UbahPassword
    Dimension induk = jDesktopPane1.getSize();
    Dimension anak = up.getSize();
    // Menetapkan lokasi UbahPassword agar berada di tengah jDesktopPane1
    up.setLocation((induk.width - anak.width) / 2, (induk.height - anak.height) / 2);
    // Menampilkan tampilan UbahPassword
    up.setVisible(true);
    }//GEN-LAST:event_Sandi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Karyawan;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem Kembali;
    private javax.swing.JMenuItem Sandi1;
    private javax.swing.JMenuItem Tema;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
