/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.Login;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Date;
import java.text.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import net.sf.jasperreports.engine.JasperReport;
/**
 *
 * @author MUHAMMAD PAHRUL GUNAWAN
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    public MenuUtama() {
        initComponents();
        //Memperbesar layar jadi layar penuh
        setExtendedState(MAXIMIZED_BOTH);
        //Mengatur judul Frame jadi "Main Menu"
        setTitle("APLIKASI TOKO BUKU AL FATIH");
        
    }
    private void centerFrameOnDesktop(JInternalFrame frame, JDesktopPane desktopPane) {
    // Mendapatkan dimensi desktopPane (induk) dan dimensi frame (anak)
    Dimension induk = desktopPane.getSize();
    Dimension anak = frame.getSize();
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    // Menentukan lokasi frame agar berada di tengah desktopPane
    int x = (induk.width - anak.width) / 2;
    int y =     0;

    // Menetapkan lokasi frame
    frame.setLocation(x, y);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MENU = new javax.swing.JMenu();
        Kembali = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        DATA = new javax.swing.JMenu();
        DataBuku = new javax.swing.JMenuItem();
        DataDist = new javax.swing.JMenuItem();
        DataPemasok = new javax.swing.JMenuItem();
        TRANSAKSI = new javax.swing.JMenu();
        Penjualan = new javax.swing.JMenuItem();
        LAPORAN = new javax.swing.JMenu();
        Pemasukan = new javax.swing.JMenuItem();
        PENGATURAN = new javax.swing.JMenu();
        Tema = new javax.swing.JMenuItem();
        UbahPassword = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bacgdound toko buku.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(51, 51, 255));
        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        menuBar.setForeground(new java.awt.Color(0, 0, 255));
        menuBar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        MENU.setBackground(new java.awt.Color(0, 0, 255));
        MENU.setForeground(new java.awt.Color(0, 0, 255));
        MENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-menu-32.png"))); // NOI18N
        MENU.setMnemonic('f');
        MENU.setText("MENU");
        MENU.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Kembali.setBackground(new java.awt.Color(0, 0, 255));
        Kembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Kembali.setForeground(new java.awt.Color(0, 0, 255));
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-back-32.png"))); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        MENU.add(Kembali);

        Keluar.setBackground(new java.awt.Color(0, 0, 255));
        Keluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(0, 0, 255));
        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-logout-32.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        MENU.add(Keluar);

        menuBar.add(MENU);

        DATA.setBackground(new java.awt.Color(0, 0, 255));
        DATA.setForeground(new java.awt.Color(0, 0, 255));
        DATA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-database-32.png"))); // NOI18N
        DATA.setText("DATA");
        DATA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        DataBuku.setBackground(new java.awt.Color(0, 0, 255));
        DataBuku.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DataBuku.setForeground(new java.awt.Color(0, 0, 255));
        DataBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-book-32.png"))); // NOI18N
        DataBuku.setText("Data Buku");
        DataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBukuActionPerformed(evt);
            }
        });
        DATA.add(DataBuku);

        DataDist.setBackground(new java.awt.Color(0, 0, 255));
        DataDist.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DataDist.setForeground(new java.awt.Color(0, 0, 255));
        DataDist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-distributor-32.png"))); // NOI18N
        DataDist.setText("Data Distributor");
        DataDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDistActionPerformed(evt);
            }
        });
        DATA.add(DataDist);

        DataPemasok.setBackground(new java.awt.Color(0, 0, 255));
        DataPemasok.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DataPemasok.setForeground(new java.awt.Color(0, 0, 255));
        DataPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-Pemasok-32 (1).png"))); // NOI18N
        DataPemasok.setText("Data Pemasok");
        DataPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPemasokActionPerformed(evt);
            }
        });
        DATA.add(DataPemasok);

        menuBar.add(DATA);

        TRANSAKSI.setBackground(new java.awt.Color(0, 0, 255));
        TRANSAKSI.setForeground(new java.awt.Color(0, 0, 255));
        TRANSAKSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-bill-32.png"))); // NOI18N
        TRANSAKSI.setText("TRANSAKSI");
        TRANSAKSI.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Penjualan.setBackground(new java.awt.Color(0, 0, 255));
        Penjualan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Penjualan.setForeground(new java.awt.Color(0, 0, 255));
        Penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-shopping-bag-32.png"))); // NOI18N
        Penjualan.setText("Penjualan");
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        TRANSAKSI.add(Penjualan);

        menuBar.add(TRANSAKSI);

        LAPORAN.setBackground(new java.awt.Color(0, 0, 255));
        LAPORAN.setForeground(new java.awt.Color(0, 0, 255));
        LAPORAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-report-32.png"))); // NOI18N
        LAPORAN.setText("LAPORAN");
        LAPORAN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Pemasukan.setBackground(new java.awt.Color(0, 0, 255));
        Pemasukan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pemasukan.setForeground(new java.awt.Color(0, 0, 255));
        Pemasukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-income-32.png"))); // NOI18N
        Pemasukan.setText("Pemasukan");
        Pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemasukanActionPerformed(evt);
            }
        });
        LAPORAN.add(Pemasukan);

        menuBar.add(LAPORAN);

        PENGATURAN.setBackground(new java.awt.Color(0, 0, 255));
        PENGATURAN.setForeground(new java.awt.Color(0, 0, 255));
        PENGATURAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-setting-32.png"))); // NOI18N
        PENGATURAN.setText("PENGATURAN");
        PENGATURAN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Tema.setBackground(new java.awt.Color(0, 0, 255));
        Tema.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Tema.setForeground(new java.awt.Color(0, 0, 255));
        Tema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-theme-32.png"))); // NOI18N
        Tema.setText("Tema");
        Tema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemaActionPerformed(evt);
            }
        });
        PENGATURAN.add(Tema);

        UbahPassword.setBackground(new java.awt.Color(0, 0, 255));
        UbahPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UbahPassword.setForeground(new java.awt.Color(0, 0, 255));
        UbahPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-password-key-32.png"))); // NOI18N
        UbahPassword.setText("Ubah Sandi");
        UbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPasswordActionPerformed(evt);
            }
        });
        PENGATURAN.add(UbahPassword);

        menuBar.add(PENGATURAN);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
      //Kembali ke FORM LOGIN
      new Login().show();
      this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_KeluarActionPerformed

    private void DataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBukuActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas DataBuku
    DataBuku DB = new DataBuku();
    // Menambahkan instance DataBuku ke dalam desktopPane
    desktopPane.add(DB);
    // Menentukan lokasi DataBuku agar berada di tengah desktopPane
    centerFrameOnDesktop(DB, desktopPane);
    // Menampilkan DataBuku
    DB.setVisible(true);
    // Fokus pada DataBuku setelah ditampilkan
    DB.toFront();
    }//GEN-LAST:event_DataBukuActionPerformed

    private void DataDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDistActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas DataDistributor
    DataDistributor DB = new DataDistributor();
    // Menambahkan instance DataDistributor ke dalam desktopPane
    desktopPane.add(DB);
    // Menentukan lokasi DataDistributor agar berada di tengah desktopPane
    centerFrameOnDesktop(DB, desktopPane);
    // Menampilkan DataDistributor
    DB.setVisible(true);
    // Fokus pada DataDistributor setelah ditampilkan
    DB.toFront();
    }//GEN-LAST:event_DataDistActionPerformed

    private void DataPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPemasokActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas DataPasok
    DataPasok DP = new DataPasok();
    // Menambahkan instance DataPasok ke dalam desktopPane
    desktopPane.add(DP);
    // Menentukan lokasi DataPasok agar berada di tengah desktopPane
    centerFrameOnDesktop(DP, desktopPane);
    // Menampilkan DataPasok
    DP.setVisible(true);
    // Fokus pada DataPasok setelah ditampilkan
    DP.toFront();
    }//GEN-LAST:event_DataPemasokActionPerformed

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas Penjualan
    Penjualan p = new Penjualan();
    // Menambahkan instance Penjualan ke dalam desktopPane
    desktopPane.add(p);
    // Menentukan lokasi Penjualan agar berada di tengah atas desktopPane
    centerFrameOnDesktop(p, desktopPane);
    // Menampilkan Penjualan
    p.setVisible(true);
    // Fokus pada Penjualan setelah ditampilkan
    p.toFront();
    }//GEN-LAST:event_PenjualanActionPerformed

    private void PemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemasukanActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas Pemasok
    Pemasukan p = new Pemasukan();
    // Menambahkan instance Pemasukan ke dalam desktopPane
    desktopPane.add(p);
    // Menentukan lokasi Pemasukan agar berada di tengah atas desktopPane
    centerFrameOnDesktop(p, desktopPane);
    // Menampilkan Pemasukan
    p.setVisible(true);
    // Fokus pada Pemasukan setelah ditampilkan
    p.toFront();
    }//GEN-LAST:event_PemasukanActionPerformed

    private void TemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemaActionPerformed
    // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas Tema
    Tema p = new Tema();
    // Menambahkan instance Tema ke dalam desktopPane
    desktopPane.add(p);
    // Menentukan lokasi Tema agar berada di tengah atas desktopPane
    centerFrameOnDesktop(p, desktopPane);
    // Menampilkan Tema
    p.setVisible(true);
    // Fokus pada Tema setelah ditampilkan
    p.toFront(); 
    }//GEN-LAST:event_TemaActionPerformed

    private void UbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPasswordActionPerformed
     // Memperbarui tampilan frame
    this.repaint();
    // Membuat instance dari kelas Tema
    UbahPassword up = new UbahPassword();
    // Menambahkan instance Tema ke dalam desktopPane
    desktopPane.add(up);
    // Menentukan lokasi Tema agar berada di tengah atas desktopPane
    centerFrameOnDesktop(up, desktopPane);
    // Menampilkan Tema
    up.setVisible(true);
    // Fokus pada Tema setelah ditampilkan
    up.toFront();
    }//GEN-LAST:event_UbahPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DATA;
    private javax.swing.JMenuItem DataBuku;
    private javax.swing.JMenuItem DataDist;
    private javax.swing.JMenuItem DataPemasok;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem Kembali;
    private javax.swing.JMenu LAPORAN;
    private javax.swing.JMenu MENU;
    private javax.swing.JMenu PENGATURAN;
    private javax.swing.JMenuItem Pemasukan;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenu TRANSAKSI;
    private javax.swing.JMenuItem Tema;
    private javax.swing.JMenuItem UbahPassword;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
