/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Scanner;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author MUHAMMAD PAHRUL GUNAWAN
 */
public class UbahPassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form UbahPassword
     */
    
    //Objek UserSession digunakan untuk mengelola informasi sesi pengguna seperti username.
    private UserSession session = new UserSession();
    String username = session.getUsername();
    private String sql;
    private koneksi kon = new koneksi(); // Koneksi ke database
    private Connection con; // Objek koneksi
    private ResultSet rs; // Hasil eksekusi query database
    private Statement stat; // Objek untuk mengeksekusi pernyataan SQL
    
    public UbahPassword() {
    initComponents();
    con = kon.con; // Inisialisasi koneksi ke database
    setTitle("Ubah Password"); // Menetapkan judul internal frame
    ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); // Menghilangkan panel atas internal frame
    this.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true)); // Menetapkan border dengan warna dan ketebalan tertentu
    try {
        FileReader fr = new FileReader("src/tema.txt");
        BufferedReader br = new BufferedReader(fr);
        if (br.readLine().equals("Light")) {
            // Tidak ada modifikasi tema untuk mode Light
        } else {
            tema(); // Terapkan modifikasi tema jika tidak dalam mode Light
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    //Methode untuk membuat semua text menjadi BIRU ketia Tema dalam mode gelap
    private void tema(){
        this.setBackground(Color.BLACK);
        jPanel1.setBackground(Color.BLACK);
        jLabel1.setForeground(Color.BLUE);
        jLabel2.setForeground(Color.BLUE);
        jLabel3.setForeground(Color.BLUE);
        jLabel4.setForeground(Color.BLUE);
        btnUbah.setBackground(Color.BLACK);
        btnUbah.setForeground(Color.BLUE);
        ImageIcon icon = new ImageIcon("src/Gambar/icons8-exit-30.png");
        jButton2.setIcon(icon);
        this.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2,true));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUbah = new javax.swing.JButton();
        PswLama = new javax.swing.JPasswordField();
        PswBaru = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        knfrmpass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        btnUbah.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(0, 0, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-ok-32.png"))); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        PswLama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PswLama.setForeground(new java.awt.Color(0, 0, 255));
        PswLama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PswLama.setToolTipText("Password Lama");
        PswLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PswLamaKeyTyped(evt);
            }
        });

        PswBaru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PswBaru.setForeground(new java.awt.Color(0, 0, 255));
        PswBaru.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PswBaru.setToolTipText("Password Baru");
        PswBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PswBaruKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("PASSWORD LAMA");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("PASSWORD BARU");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("KONFIRMASI PASSWORD");

        knfrmpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        knfrmpass.setForeground(new java.awt.Color(0, 0, 255));
        knfrmpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        knfrmpass.setToolTipText("Konfirmasi Password Baru");
        knfrmpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                knfrmpassKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-password-key-32.png"))); // NOI18N
        jLabel1.setText("UBAH SANDI");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-exit-30.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_MacOS_Close_30px_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PswBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PswLama, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(knfrmpass))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PswLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PswBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(knfrmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int id = session.getId(); // Mendapatkan ID pengguna dari sesi
        // Memeriksa apakah terdapat data yang belum diisi
        if (PswLama.getText().isEmpty() || PswBaru.getText().isEmpty() || knfrmpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ada data yang belum di isi", "Informasi", JOptionPane.ERROR_MESSAGE);
        } else {
        // Memeriksa apakah password baru dan konfirmasi password sama
        if (PswBaru.getText().equals(knfrmpass.getText())) {
            try {
                // Mengambil password lama dari database berdasarkan ID pengguna
                sql = "SELECT password FROM kasir WHERE id='" + id + "'";
                stat = con.createStatement();
                rs = stat.executeQuery(sql);
                if (rs.next()) {
                    // Memeriksa apakah password lama sesuai dengan yang dimasukkan
                    if (PswLama.getText().equals(rs.getString("password"))) {
                        // Mengupdate password baru ke dalam database
                        sql = "UPDATE kasir SET password='" + knfrmpass.getText() + "' WHERE id='" + id + "'";
                        stat = con.createStatement();
                        stat.executeUpdate(sql);
                        // Menutup internal frame dan menampilkan pesan sukses
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Sukses Ubah Password");
                    } else {
                        JOptionPane.showMessageDialog(null, "Password lama salah");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password tidak sama");
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void PswLamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PswLamaKeyTyped
        PswLama.setEchoChar('*');
    }//GEN-LAST:event_PswLamaKeyTyped

    private void PswBaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PswBaruKeyTyped
        PswBaru.setEchoChar('*');
    }//GEN-LAST:event_PswBaruKeyTyped

    private void knfrmpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_knfrmpassKeyTyped
        knfrmpass.setEchoChar('*');
    }//GEN-LAST:event_knfrmpassKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PswBaru;
    private javax.swing.JPasswordField PswLama;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField knfrmpass;
    // End of variables declaration//GEN-END:variables
}
